apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    image: gcr.io/xxxxxxxxxx/jenkins-agent:latest
    args: ['\$(JENKINS_SECRET)', '\$(JENKINS_NAME)']
    resources:
      requests:
        cpu: "0.1"   
        memory: "256Mi"  
      limits:
        cpu: "0.5"   
        memory: "1Gi" 
  - name: jenkins-agent
    image: gcr.io/xxxxxxxxxx/jenkins-agent:latest
    securityContext:
      privileged: true
    tty: true
    resources:
      requests:
        cpu: "0.1" 
        memory: "512Mi" 
      limits:
        cpu: "1" 
        memory: "2Gi"
  serviceAccountName: jenkins-admin
